name: Deploy To Heroku

on:
  push:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Use Node.js }
        uses: actions/setup-node@v1
        with:
          node-version: 13.x
      - name: npm install
        run: npm i
      - name: npm build
        run: npm run build
        env:
          CI: ""
      - name: Deploy to heroku
        uses: akhileshns/heroku-deploy@v3.2.6
        with:
          heroku_api_key: ${{secrets.HEROKU_API_TOKEN}}
          heroku_app_name: "snippetserve"
          heroku_email: ${{secrets.HEROKU_EMAIL}}
